### ISSUE TITLE
`defaultState` not passed to `handleAction` from  `handleActions`

### ISSUE THREAD

**Issue by vanthiyathevan** [acdlite/redux-actions#108]
Shouldn't it be passed to `handleAction` from `handleActions`?

**Comment by yangmillstheory** [comment]
https://github.com/acdlite/redux-actions#handleactionsreducermap-defaultstate

I don't think this would work.

The `defaultState` parameter is passed to the combined (reduced) reducer. 

Since we're using [reduce-reducers](https://github.com/acdlite/reduce-reducers) which runs the reducers serially, it will actually be passed to the first reducer in the chain in case the state passed in was `undefined`.

Reducers need to return a new state object (not `undefined`):

> (previousState, action) => newState

That's from the [Redux docs](http://redux.js.org/docs/basics/Reducers.html). Therefore, there will never be a need to pass the same `defaultState` to remaining reducers in the chain.
