### ISSUE TITLE
Readme createActions example incorrect

### ISSUE THREAD

**Issue by amit1911** [acdlite/redux-actions#172]
I just noticed that in the example section for `createActions` the following example is incorrect
```
expect(actionTwo('first', 'second')).to.deep.equal({
  type: 'ACTION_TWO',
  payload: ['first'], // incorrect - no array required
  meta: { second: 'second' }
});
```
The payload is an array with the string `'first'` whereas it should be equal to just the string `'first'`.
Correct version is as follows:
```
expect(actionTwo('first', 'second')).to.deep.equal({
  type: 'ACTION_TWO',
  payload: 'first', // correct
  meta: { second: 'second' }
});
```

**Comment by yangmillstheory** [comment]
Good reading. I think the payload creator was meant to wrap the value in an array.  

These are pulled from the tests; what do they say? 

Feel free to submit a correction.

**Comment by vinnymac** [comment]
@amit1911 @yangmillstheory this is expected behavior due to the transform in the sample code.
<img width="528" alt="screen shot 2017-06-28 at 6 47 49 pm" src="https://user-images.githubusercontent.com/1832781/27663859-57336ab6-5c32-11e7-9bcf-a3427623bfcb.png">

This is the part of the documentation that explains why this happens
```js
// array form
  ACTION_TWO: [
    (first) => [first],             // payload
    (first, second) => ({ second }) // meta
  ],
```

I think this should be closed.

**Comment by yangmillstheory** [comment]
Thanks @vinnymac
