### ISSUE TITLE
it would be nice if the metaCreator was also the identity function if not specified

### ISSUE THREAD

**Issue by faceyspacey** [acdlite/redux-actions#181]

**Comment by just4fun** [comment]
I'd also like `metaCreator` will be identity function if not specified, since sometimes I want to pass some data as meta, not payload.

Finally I found `identity` function which provided by lodash will only return first argument it receives, so I think keep `metaCreator` with no default function is better.

Here is my code.

```javascript
// treat 2nd argument as `meta` field
export const success = createAction(REQUEST_COMPELTED, null, (...args) => args[1]);
```

```javascript
// I used redux-saga and this line likes ajax successful callback.
// with the action I created with redux-actions above, `data`
// will be `payload`, `{ whatever }` will be `meta`.
yield put(resource.success(data, { whatever }));
```
