### ISSUE TITLE
Not understanding the purpose of redux-actions...

### ISSUE THREAD

**Issue by joetidee** [acdlite/redux-actions#184]
Apologies, but it's not obvious to me what the redux-actions package does. For example, I currnelty create my actions like this:

```
export function doSomething(id) {
    return { type: 'DO_SOMETHING', payload: id }
}
```

So how does this package improve on this?

**Comment by jkusachi** [comment]
When you're working with Redux, you're going to have many actions, with different shapes

Because of this, @acdlite proposed flux standard actions (FSA) - https://github.com/acdlite/flux-standard-action

As stated, "It's much easier to work with Flux actions if we can make certain assumptions about their shape"

Regarding redux-actions, it does what it says it does: "Wraps an action creator so that its return value is the payload of a Flux Standard Action."

Consider them more like helper functions.

So rather than having to write

```
function doSomething(id) {
    return {
      type: 'DO_SOMETHING',
      payload: id 
    }
}
```

you can just write
`const doSomething = createAction('DO_SOMETHING')`

If you want to supply multiple arguments to your action, you can look into the `payloadCreator` piece.

This is a brief writeup, reading through the readme you'll read more, but this hopefully helps :)

**Comment by xiaoke88** [comment]
actionCreator factory like this
```js
let createActionCreator=(type,...argsName)=>{
    let action ={type};
    return (...args)=>{
        argsName.forEach((v,i)=>{
            action[v] = args[i];
        });
        return action;
    }
}
```

**Comment by joetidee** [comment]
Does it allow you factor in asnyc calls, such as:

```
export function doSomething() {
    return (dispatch, getState) => {
        doFetch({
            url: "/api",
            callback: function (response) {
                dispatch({
                    ...
                });
            },
            error: function (error) {
                dispatch({
                    ...
                });
            }
        });
    }
}
```

**Comment by yangmillstheory** [comment]
No, I'd suggest looking at redux-thunk or redux-saga for that. This library is primarily concerned with:

- mitigating typical boilerplate associated with Redux apps
- adhering to and supporting the Flux Standard Action spec

**Comment by joetidee** [comment]
So if you use redux-actions, you cannot perform async actions?

**Comment by gouegd** [comment]
An action is just a JS object with a `type` property and perhaps others. So there's no "async action" but you can create actions asynchronously.

You can do it manually or with the helpers that @yangmillstheory noted above.
`redux-thunk` lets you create actions based on other actions.
`redux-promise` lets you create actions based on promises.
`redux-saga` works with generators and can replace both libs above, with more powerful abstractions to handle async events, but in a way that most JS devs will need some time to understand properly.
