### ISSUE TITLE
Namespace for reducers

### ISSUE THREAD

**Issue by tsarapke** [acdlite/redux-actions#199]
So, you have mentioned that there is available possibility to add namespace for action creators. Like below (for example):
```javascript
const actionCreators = createActions({
  USER: {
    CREATE_ITEM: data => ({ data }) ,
    DELETE_ITEM: ( ... ) => ...,
    GET_LIST: ( ... ) => ...,
    ...
  }
});
```
But how I can create namespace for reducers, like for such trivial operations as CRUD. Example:
```javascript
// Creating CRUD reducer template
const crudReducerTemplate = {
   CREATE_ITEM: (state, action ) => ...,
   DELETE_ITEM: ( ... ) => ...,
   GET_LIST: ( ... ) => ...,
   ...
};

// Creating reducer for users' CRUD operations
const userReducers = handleAction({
   USER: {
      ...crudReducerTemplate
   }
}, /* Default state here */);

// Creating reducer for articles' CRUD operations
const articleReducers = handleAction({
   ARTICLE: {
      ...crudReducerTemplate
   }
}, /* Default state here */);
```
Is it possible to do with your utile? Thanks.

**Comment by akomm** [comment]
Since handleActions simply creates a reducer, you can use combineReducers from 'redux' package:

```js
const rootReducer = combineReducers({
  USER: crudeReducerTemplate,
  ARTICLE: cruteReducerTemplate
});
```

Obviously combineReducers also creates a reducer, so you can nest it deeper if you need to.

**Comment by akomm** [comment]
There is a possibility to group reducers as you want using combineReducers from "redux" npm package. The problem is the action identity when you reuse reducers. You also have to duplicate-namespace actions.

Even though often you have "1:1 relation" between action/reducer, by design reducers can act on any action. You could make special factories which could generate what you want. But any approach I image feels to overcomplicated as there are other, easier approaches to solve this problem.

You could turn the whole structure. Instead of namespacing reducers, namespacing actions, duplicating code for generic stuff, I would create a single action set and reducer for generic states and namespace them under the reducer itself. Check redux-form or apollo-client as an example. redux-form manages all different form states under a single "form" key and namespaces the form states inside via a key (formId) => state. 

In your case you would have state { entities: { article: ..., user: ...  } 

Even though what you would could be done at first glance, I'm not sure if that makes any sense.

**Comment by tsarapke** [comment]
@akomm Thanks for your attention and explanation. "redux-form" architecture is suitable solution for me. Will investigate its principles of work.

**Comment by akomm** [comment]
Before you go to much into the docs of redux-form - just to solve this problem - give your actions an additional namespace payload variable and let the reducer write state nested inside a key from that payload variable.

**Comment by tsarapke** [comment]
@akomm Thanks again. I'll try it. Also I've found [multireducer](https://github.com/erikras/multireducer) library. Seems it's like that I'm want and looking for.

**Comment by akomm** [comment]
This does exact that mapping key mapping I was talking about :)

**Comment by yangmillstheory** [comment]
Thanks @akomm
