### ISSUE TITLE
ES6 defaults

### ISSUE THREAD

**Issue by djake** [acdlite/redux-actions#225]
Would you be amenable to altering, eliminating, or making optional the defaultState invariant check in [handleAction](https://github.com/acdlite/redux-actions/blob/master/src/handleAction.js#L12) so that we can set the default state parameter in the reducer function definition instead?

**Comment by yangmillstheory** [comment]
Not without reason, I guess. Is there a good reason to change the behavior?

**Comment by djake** [comment]
The reason I would like to change it (you'll have to tell me if it's good) is that I prefer 
`handleAction(MY_ACTION, (state = '', action = {}) => action.payload.someProp`
to
`handleAction(MY_ACTION, (state, action) => action.payload.someProp, '')`. And, I have tests for the undefined case for reducers so this check is all dead weight for me at the moment.

I think the only way to preserve the intended behavior of the invariant check and allow the function to set its own defaults would be to actually run reducer function with `undefined` state and test the output.

**Comment by yangmillstheory** [comment]
Are you testing the reducer function parameter to `handleAction`, or the output of `handleAction` itself. Either way, I think if there's no strong case to make this change, we should just leave it as is. The change would also impact https://github.com/acdlite/redux-actions/blob/a0a9f00246c7e760bd1dfc6a630652c1520bb2b3/src/handleActions.js#L7.

IMO it's good to have `defaultState` as a required parameter, so that we can enforce that it's always present.

**Comment by djake** [comment]
Ok. Thanks for the quick replies!
