### ISSUE TITLE
how to set meta property?

### ISSUE THREAD

**Issue by ustccjw** [acdlite/redux-actions#3]
As title, how to set meta property?

**Comment by clearjs** [comment]
@ustccjw Could you please elaborate on the problem and context that you have? `meta` is just a field in a plain action object, its "properties" are fields as well.

**Comment by ustccjw** [comment]
return (...args) => ({
        type,
        payload: finalActionCreator(...args)
    })

I mean, when use `createAction`, the return value is payload, i want to pass meta property, how can i do?

**Comment by acdlite** [comment]
@clearjs I think @ustccjw wants to be able to specify meta using `createAction()`. I've been thinking about it, because it's particularly important for async actions, where you need the ability to pass certain metadata to the `throw()` handler, and to the `begin()` handler once we implement https://github.com/acdlite/redux-actions/issues/2

@johanneslumpe and I discussed this on Slack, and the idea we come up with is to have an optional second parameter to `createAction()` that accepts the same parameters as the action creator, but it returns a plain object whose contents will be added to the `meta` field:

```js
const addTodo = createAction('ADD_TODO', (text, id) => ({ text, id }), (text, id) => ({ id }));
addTodo('Use Redux', 123); // { type: 'ADD_TODO', payload: { text: 'Use Redux', id: 123 }, meta: { id: 123 } }
```

**Comment by acdlite** [comment]
That way, for example, if the action fails (say you're using redux-promise and the promise rejected) the reducer still has access to the meta object, which it can use to undo an optimistic update:

```js
{ type: 'ADD_TODO', error: true, payload: error, meta: { id: 123 } }
```

**Comment by clearjs** [comment]
@ustccjw @acdlite Thanks. Sorry, I was still thinking in the context of FSA and thus didn't get it at first.

**Comment by acdlite** [comment]
Oops, forgot to close this, but v0.8 added support for a meta creator https://github.com/acdlite/redux-actions/releases/tag/v0.7.0
