### ISSUE TITLE
Proposal: mechanism for handling multiple actions with the same reducer.

### ISSUE THREAD

**Issue by lukewestby** [acdlite/redux-actions#31]
Hi all!

I'd like to propose a new feature to allow handling multiple actions with the same reducer in the case that someone has very general, over-arching properties of their state.

For example, when using redux on its own I've found it useful to have a `loading` property which gets reduced like this:

```javascript
function loading(state = false, action) {
  switch(action.type) {
  case LOAD_SOMETHING_START:
  case LOAD_SOMETHING_ELSE_START:
    return true;

  case LOAD_SOMETHING_COMPLETE:
  case LOAD_SOMETHING_ELSE_COMPLETE:
    return false;

  default:
    return state;
  }
}
```

I find this preferable to invoking an action to update `loading` within a composite/async action using redux-thunk because I would prefer not to have my state's other properties know about the `loading` property and keep that logic central to the reducer for `loading`.

Initially I'd like to propose being able to define an action handler with a name that contains a delimiter like `|`. To illustrate with the previous example:

```javascript
handleActions({
  'LOAD_SOMETHING_START | LOAD_SOMETHING_ELSE_START': () => true,
  'LOAD_SOMETHING_COMPLETE | LOAD_SOMETHING_ELSE_COMPLETE': () => false
}, false);
```

Alternatively, if it would be preferable not to expose the details about how to delimit action names, a function `combineActions()` might help:

```javascript
const startActions = combineActions('LOAD_SOMETHING_START', 'LOAD_SOMETHING_ELSE_START');
const completeActions = combineActions('LOAD_SOMETHING_COMPLETE', 'LOAD_SOMETHING_ELSE_COMPLETE');

handleActions({
  [startActions]: () => true,
  [completeActions]: () => false
}, false);
```

What do you think? I'd be thrilled to submit a PR for this if we agree it would be worthwhile.

**Comment by davezuko** [comment]
:+1: I like this a lot, and it's something that has kept me from fully adopting a `createReducer`/`handleActions` abstraction in my applications.

I know this issue is fairly dead, but there is interest :)

**Comment by bradwheel** [comment]
:+1: Here's some additional interest

**Comment by mwalsher** [comment]
:+1:

**Comment by obrin** [comment]
:+1:

**Comment by weslleyaraujo** [comment]
thats very very useful 👍

@lukewestby is there any wip on this?
if not so, can I start working on it?

**Comment by yangmillstheory** [comment]
👍

**Comment by yangmillstheory** [comment]
I was thinking that a conventional delimiter like `|` could work, but there's no obvious way for library users to join action creators (which can be used as inputs to `handleActions` or `handleAction`) since the way an action creator stores its type (via `toString`) seems encapsulated from the library user. 

So, I think the `combineActions` approach seems the most reasonable.

**Comment by yangmillstheory** [comment]
I've been using this feature at work via a fork of this project and it's turned out great for DRY'ing up our reducers (especially when using reducer composition). I'll see if I can contribute this feature back to the repository.

[As mentioned above though](https://github.com/acdlite/redux-actions/issues/31#issuecomment-230199255), I don't see a cleaner path to doing this than the `combineActions` approach.
